### PR TITLE
Missing argument allowNonPublicAccessors when creating ObjectAccessor…

### LINKED ISSUE #12: allowNonPublicAccessors does not work  with ObjectAccessor
```
Here is your code
As you can see allowNonPublicAccessors is not used

    /// <summary>
    /// Wraps an individual object, allowing by-name access to that instance
    /// 
    /// </summary>
    public static ObjectAccessor Create(object target, bool allowNonPublicAccessors)
    {
      if (target == null)
        throw new ArgumentNullException("target");
      IDynamicMetaObjectProvider target1 = target as IDynamicMetaObjectProvider;
      if (target1 != null)
        return (ObjectAccessor) new ObjectAccessor.DynamicWrapper(target1);
      else
        return (ObjectAccessor) new ObjectAccessor.TypeAccessorWrapper(target, TypeAccessor.Create(target.GetType()));
    }
```

Original issue reported on code.google.com by `P.Le...@zelenski.ru` on 28 Nov 2014 at 3:20

### PR DESCRIPTION
**Pull request by alercunha**
… (fixes #12)

### CODE REVIEW

**Comment by mgravell** [comment]
Looks legit, thanks

**Comment by alercunha** [comment]
Hi Marc,

Since we're here, I'm using fast-member in a project where I do a lot of
things dynamically. It's a dynamic REST API + CRUD HTML5 interface on top
of a SQL database, quite cool actually.

One thing I need a lot is retrieving and setting values in a TryGet
fassion. Is that something you'd be willing to include in FastMember?

Unfortunately I'm not experienced with IL Emit so I'm struggling to do a
method with an output parameter implemented that way.
Maybe you can give me some hints so I can try implementing it then do a
pull request if you're interested.

Anyway, I'm sure you're busy with all sort of things, I appreciate any help.

Thanks,
Alex.

**Comment by mgravell** [comment]
What is the intended API here? Something like:

book TryGet(string name, out object value);

- true if found and invoked successfully
- false ID not found or exception occurred; in the latter case, value is
the exception

?

Or...?

**Comment by mgravell** [comment]
Dammit, /s/book/bool - #damnyouautocorrect

**Comment by alercunha** [comment]
Well, I wouldn't return the exception. Just let it throw.
The result would be true only if a getter with that name is found. False
otherwise. Which means you're forwarding the TryGet to the name/index map
(Dictionary<string, int>).

I think that's more consistent right?

Might sound weird but I also need a bool TrySet(string name, obj value)
which sets the value only if a setter name exists.
I admit it's itchy to have a TrySet so maybe a ContainsProperty(string
name) would suffice.

Cheers,
Alex.

**Pull request merged**
