### PR TITLE
Moving to .NET Core RTM

### PR DESCRIPTION
**Pull request by agoretsky**
Please check it out

### CODE REVIEW

**Comment by mgravell** [comment]
Looks legit and much appreciated; the main thing that I would question would be the choice of netstandard1.6 - it feels like this should actually be fine a lot lower - my hunch says 1.3; thoughts?

**Comment by agoretsky** [comment]
I have changed it to netstandard1.3. Could you merge it and public to nuget?

**Comment by mgravell** [comment]
Sounds good, thanks - much appreciated

**Comment by mgravell** [comment]
1.1.0 deployed; thanks!

**Comment by CELCAT** [comment]
Using latest stable 1.1.0 on a .net standard 2.0 (preview 1) class library project, when using SqlDbType, ended up with Error CS0433 The type 'SqlDbType' exists in both 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by CELCAT** [comment]
Issue resolved by explictly install the latest System.Data.SqlClient v4.4.0-preview1 nuget package which updates all the dependencies. Thx.

**Pull request merged**
