### PR TITLE
Add library compatibility for Net20

### PR DESCRIPTION
**Pull request by IkerCelorrio**
Add library compatibility to net20.

### CODE REVIEW

**Comment by mgravell** [comment]
I don't like that this declares `System.Runtime.CompilerServices.ExtensionAttribute`; that is going to cause chaos with anyone who has already had to declare that  to make their code compile. I think it would be better to simply forsake extension methods for 2.0 - or to import those from a MS common package (if one exists). Thoughts?

**Comment by IkerCelorrio** [comment]
Yes, i think is little messy, but in net20 i have not found any MS (net20) library with that attribute.

If I forsake extensions methods it would change all extension methods to standard static methods and calls

```public static bool _IsValueType(this Type type)``` will change to ```public static bool _IsValueType(Type type)```

And the use ``field.FieldType._IsValueType()``` will change to ```TypeHelpers._isValueType(field.FieldType)```or 
```_isValueType(field.FieldType)``` if I use an ```using static FastMember.TypeHelpers``` with C#6.0 or above

This is much more change to the code, and will be too messy to do with #if #enif preprocessor clauses. Otherside I could branch code files by framework by this could weak code maintenance and readibility

I could write both options if you like.
Which option do you want to see first? :-)

**Comment by mgravell** [comment]
Thanks; that's a huge improvement. Avoids a big problem.

**Comment by IkerCelorrio** [comment]
C# 6.0 save us with ```static using statements``` :sweat_smile:

**Pull request merged**
